ARG BASE_IMAGE=golang:1.20-alpine

FROM ${BASE_IMAGE}

RUN apk add --no-cache bash

RUN go install github.com/jstemmer/go-junit-report/v2@v2.0.0 && go install github.com/boumenot/gocover-cobertura@v1.2.0

WORKDIR /src
COPY go.* .
RUN go mod download
COPY . .

CMD ./scripts/test
