// Code generated by mockery v2.26.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	conjur "github.cyberng.com/Conjur-Enterprise/conjur-service-broker-go/pkg/conjur"
)

// Bind is an autogenerated mock type for the Bind type
type Bind struct {
	mock.Mock
}

// BindHostPolicy provides a mock function with given fields:
func (_m *Bind) BindHostPolicy() (*conjur.Policy, error) {
	ret := _m.Called()

	var r0 *conjur.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func() (*conjur.Policy, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *conjur.Policy); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conjur.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BindSpacePolicy provides a mock function with given fields:
func (_m *Bind) BindSpacePolicy() (*conjur.Policy, error) {
	ret := _m.Called()

	var r0 *conjur.Policy
	var r1 error
	if rf, ok := ret.Get(0).(func() (*conjur.Policy, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *conjur.Policy); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conjur.Policy)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBindHostPolicy provides a mock function with given fields:
func (_m *Bind) DeleteBindHostPolicy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// HostExists provides a mock function with given fields:
func (_m *Bind) HostExists() (bool, error) {
	ret := _m.Called()

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func() (bool, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewBind interface {
	mock.TestingT
	Cleanup(func())
}

// NewBind creates a new instance of Bind. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBind(t mockConstructorTestingTNewBind) *Bind {
	mock := &Bind{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
