// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cyberark/conjur-service-broker-go/pkg/conjur"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBind creates a new instance of MockBind. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBind(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBind {
	mock := &MockBind{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBind is an autogenerated mock type for the Bind type
type MockBind struct {
	mock.Mock
}

type MockBind_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBind) EXPECT() *MockBind_Expecter {
	return &MockBind_Expecter{mock: &_m.Mock}
}

// BindHostPolicy provides a mock function for the type MockBind
func (_mock *MockBind) BindHostPolicy() (*conjur.Policy, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BindHostPolicy")
	}

	var r0 *conjur.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*conjur.Policy, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *conjur.Policy); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conjur.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBind_BindHostPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindHostPolicy'
type MockBind_BindHostPolicy_Call struct {
	*mock.Call
}

// BindHostPolicy is a helper method to define mock.On call
func (_e *MockBind_Expecter) BindHostPolicy() *MockBind_BindHostPolicy_Call {
	return &MockBind_BindHostPolicy_Call{Call: _e.mock.On("BindHostPolicy")}
}

func (_c *MockBind_BindHostPolicy_Call) Run(run func()) *MockBind_BindHostPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBind_BindHostPolicy_Call) Return(policy *conjur.Policy, err error) *MockBind_BindHostPolicy_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *MockBind_BindHostPolicy_Call) RunAndReturn(run func() (*conjur.Policy, error)) *MockBind_BindHostPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// BindSpacePolicy provides a mock function for the type MockBind
func (_mock *MockBind) BindSpacePolicy() (*conjur.Policy, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BindSpacePolicy")
	}

	var r0 *conjur.Policy
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*conjur.Policy, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *conjur.Policy); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conjur.Policy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBind_BindSpacePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BindSpacePolicy'
type MockBind_BindSpacePolicy_Call struct {
	*mock.Call
}

// BindSpacePolicy is a helper method to define mock.On call
func (_e *MockBind_Expecter) BindSpacePolicy() *MockBind_BindSpacePolicy_Call {
	return &MockBind_BindSpacePolicy_Call{Call: _e.mock.On("BindSpacePolicy")}
}

func (_c *MockBind_BindSpacePolicy_Call) Run(run func()) *MockBind_BindSpacePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBind_BindSpacePolicy_Call) Return(policy *conjur.Policy, err error) *MockBind_BindSpacePolicy_Call {
	_c.Call.Return(policy, err)
	return _c
}

func (_c *MockBind_BindSpacePolicy_Call) RunAndReturn(run func() (*conjur.Policy, error)) *MockBind_BindSpacePolicy_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBindHostPolicy provides a mock function for the type MockBind
func (_mock *MockBind) DeleteBindHostPolicy() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteBindHostPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBind_DeleteBindHostPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBindHostPolicy'
type MockBind_DeleteBindHostPolicy_Call struct {
	*mock.Call
}

// DeleteBindHostPolicy is a helper method to define mock.On call
func (_e *MockBind_Expecter) DeleteBindHostPolicy() *MockBind_DeleteBindHostPolicy_Call {
	return &MockBind_DeleteBindHostPolicy_Call{Call: _e.mock.On("DeleteBindHostPolicy")}
}

func (_c *MockBind_DeleteBindHostPolicy_Call) Run(run func()) *MockBind_DeleteBindHostPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBind_DeleteBindHostPolicy_Call) Return(err error) *MockBind_DeleteBindHostPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBind_DeleteBindHostPolicy_Call) RunAndReturn(run func() error) *MockBind_DeleteBindHostPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// HostExists provides a mock function for the type MockBind
func (_mock *MockBind) HostExists() (bool, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HostExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (bool, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBind_HostExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HostExists'
type MockBind_HostExists_Call struct {
	*mock.Call
}

// HostExists is a helper method to define mock.On call
func (_e *MockBind_Expecter) HostExists() *MockBind_HostExists_Call {
	return &MockBind_HostExists_Call{Call: _e.mock.On("HostExists")}
}

func (_c *MockBind_HostExists_Call) Run(run func()) *MockBind_HostExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBind_HostExists_Call) Return(b bool, err error) *MockBind_HostExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockBind_HostExists_Call) RunAndReturn(run func() (bool, error)) *MockBind_HostExists_Call {
	_c.Call.Return(run)
	return _c
}
