// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cyberark/conjur-service-broker-go/pkg/conjur"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// FromBindingID provides a mock function for the type MockClient
func (_mock *MockClient) FromBindingID(bindingID string) (conjur.Bind, error) {
	ret := _mock.Called(bindingID)

	if len(ret) == 0 {
		panic("no return value specified for FromBindingID")
	}

	var r0 conjur.Bind
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (conjur.Bind, error)); ok {
		return returnFunc(bindingID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) conjur.Bind); ok {
		r0 = returnFunc(bindingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conjur.Bind)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bindingID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_FromBindingID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromBindingID'
type MockClient_FromBindingID_Call struct {
	*mock.Call
}

// FromBindingID is a helper method to define mock.On call
//   - bindingID string
func (_e *MockClient_Expecter) FromBindingID(bindingID interface{}) *MockClient_FromBindingID_Call {
	return &MockClient_FromBindingID_Call{Call: _e.mock.On("FromBindingID", bindingID)}
}

func (_c *MockClient_FromBindingID_Call) Run(run func(bindingID string)) *MockClient_FromBindingID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_FromBindingID_Call) Return(bind conjur.Bind, err error) *MockClient_FromBindingID_Call {
	_c.Call.Return(bind, err)
	return _c
}

func (_c *MockClient_FromBindingID_Call) RunAndReturn(run func(bindingID string) (conjur.Bind, error)) *MockClient_FromBindingID_Call {
	_c.Call.Return(run)
	return _c
}

// NewBind provides a mock function for the type MockClient
func (_mock *MockClient) NewBind(orgID string, spaceID string, bindingID string, enableSpaceIdentity bool) conjur.Bind {
	ret := _mock.Called(orgID, spaceID, bindingID, enableSpaceIdentity)

	if len(ret) == 0 {
		panic("no return value specified for NewBind")
	}

	var r0 conjur.Bind
	if returnFunc, ok := ret.Get(0).(func(string, string, string, bool) conjur.Bind); ok {
		r0 = returnFunc(orgID, spaceID, bindingID, enableSpaceIdentity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conjur.Bind)
		}
	}
	return r0
}

// MockClient_NewBind_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewBind'
type MockClient_NewBind_Call struct {
	*mock.Call
}

// NewBind is a helper method to define mock.On call
//   - orgID string
//   - spaceID string
//   - bindingID string
//   - enableSpaceIdentity bool
func (_e *MockClient_Expecter) NewBind(orgID interface{}, spaceID interface{}, bindingID interface{}, enableSpaceIdentity interface{}) *MockClient_NewBind_Call {
	return &MockClient_NewBind_Call{Call: _e.mock.On("NewBind", orgID, spaceID, bindingID, enableSpaceIdentity)}
}

func (_c *MockClient_NewBind_Call) Run(run func(orgID string, spaceID string, bindingID string, enableSpaceIdentity bool)) *MockClient_NewBind_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_NewBind_Call) Return(bind conjur.Bind) *MockClient_NewBind_Call {
	_c.Call.Return(bind)
	return _c
}

func (_c *MockClient_NewBind_Call) RunAndReturn(run func(orgID string, spaceID string, bindingID string, enableSpaceIdentity bool) conjur.Bind) *MockClient_NewBind_Call {
	_c.Call.Return(run)
	return _c
}

// NewProvision provides a mock function for the type MockClient
func (_mock *MockClient) NewProvision(orgID string, spaceID string, orgName *string, spaceName *string) conjur.Provision {
	ret := _mock.Called(orgID, spaceID, orgName, spaceName)

	if len(ret) == 0 {
		panic("no return value specified for NewProvision")
	}

	var r0 conjur.Provision
	if returnFunc, ok := ret.Get(0).(func(string, string, *string, *string) conjur.Provision); ok {
		r0 = returnFunc(orgID, spaceID, orgName, spaceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conjur.Provision)
		}
	}
	return r0
}

// MockClient_NewProvision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewProvision'
type MockClient_NewProvision_Call struct {
	*mock.Call
}

// NewProvision is a helper method to define mock.On call
//   - orgID string
//   - spaceID string
//   - orgName *string
//   - spaceName *string
func (_e *MockClient_Expecter) NewProvision(orgID interface{}, spaceID interface{}, orgName interface{}, spaceName interface{}) *MockClient_NewProvision_Call {
	return &MockClient_NewProvision_Call{Call: _e.mock.On("NewProvision", orgID, spaceID, orgName, spaceName)}
}

func (_c *MockClient_NewProvision_Call) Run(run func(orgID string, spaceID string, orgName *string, spaceName *string)) *MockClient_NewProvision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockClient_NewProvision_Call) Return(provision conjur.Provision) *MockClient_NewProvision_Call {
	_c.Call.Return(provision)
	return _c
}

func (_c *MockClient_NewProvision_Call) RunAndReturn(run func(orgID string, spaceID string, orgName *string, spaceName *string) conjur.Provision) *MockClient_NewProvision_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateConnectivity provides a mock function for the type MockClient
func (_mock *MockClient) ValidateConnectivity() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ValidateConnectivity")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_ValidateConnectivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateConnectivity'
type MockClient_ValidateConnectivity_Call struct {
	*mock.Call
}

// ValidateConnectivity is a helper method to define mock.On call
func (_e *MockClient_Expecter) ValidateConnectivity() *MockClient_ValidateConnectivity_Call {
	return &MockClient_ValidateConnectivity_Call{Call: _e.mock.On("ValidateConnectivity")}
}

func (_c *MockClient_ValidateConnectivity_Call) Run(run func()) *MockClient_ValidateConnectivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_ValidateConnectivity_Call) Return(err error) *MockClient_ValidateConnectivity_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_ValidateConnectivity_Call) RunAndReturn(run func() error) *MockClient_ValidateConnectivity_Call {
	_c.Call.Return(run)
	return _c
}
