// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	conjur "github.cyberng.com/Conjur-Enterprise/conjur-service-broker-go/pkg/conjur"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// FromBindingID provides a mock function with given fields: bindingID
func (_m *Client) FromBindingID(bindingID string) (conjur.Bind, error) {
	ret := _m.Called(bindingID)

	var r0 conjur.Bind
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (conjur.Bind, error)); ok {
		return rf(bindingID)
	}
	if rf, ok := ret.Get(0).(func(string) conjur.Bind); ok {
		r0 = rf(bindingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conjur.Bind)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(bindingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBind provides a mock function with given fields: orgID, spaceID, bindingID, enableSpaceIdentity
func (_m *Client) NewBind(orgID string, spaceID string, bindingID string, enableSpaceIdentity bool) conjur.Bind {
	ret := _m.Called(orgID, spaceID, bindingID, enableSpaceIdentity)

	var r0 conjur.Bind
	if rf, ok := ret.Get(0).(func(string, string, string, bool) conjur.Bind); ok {
		r0 = rf(orgID, spaceID, bindingID, enableSpaceIdentity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conjur.Bind)
		}
	}

	return r0
}

// NewProvision provides a mock function with given fields: orgID, spaceID, orgName, spaceName
func (_m *Client) NewProvision(orgID string, spaceID string, orgName *string, spaceName *string) conjur.Provision {
	ret := _m.Called(orgID, spaceID, orgName, spaceName)

	var r0 conjur.Provision
	if rf, ok := ret.Get(0).(func(string, string, *string, *string) conjur.Provision); ok {
		r0 = rf(orgID, spaceID, orgName, spaceName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conjur.Provision)
		}
	}

	return r0
}

// ValidateConnectivity provides a mock function with given fields:
func (_m *Client) ValidateConnectivity() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
