// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvision creates a new instance of MockProvision. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvision(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvision {
	mock := &MockProvision{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvision is an autogenerated mock type for the Provision type
type MockProvision struct {
	mock.Mock
}

type MockProvision_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvision) EXPECT() *MockProvision_Expecter {
	return &MockProvision_Expecter{mock: &_m.Mock}
}

// ProvisionHostPolicy provides a mock function for the type MockProvision
func (_mock *MockProvision) ProvisionHostPolicy() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProvisionHostPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvision_ProvisionHostPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvisionHostPolicy'
type MockProvision_ProvisionHostPolicy_Call struct {
	*mock.Call
}

// ProvisionHostPolicy is a helper method to define mock.On call
func (_e *MockProvision_Expecter) ProvisionHostPolicy() *MockProvision_ProvisionHostPolicy_Call {
	return &MockProvision_ProvisionHostPolicy_Call{Call: _e.mock.On("ProvisionHostPolicy")}
}

func (_c *MockProvision_ProvisionHostPolicy_Call) Run(run func()) *MockProvision_ProvisionHostPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvision_ProvisionHostPolicy_Call) Return(err error) *MockProvision_ProvisionHostPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvision_ProvisionHostPolicy_Call) RunAndReturn(run func() error) *MockProvision_ProvisionHostPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// ProvisionOrgSpacePolicy provides a mock function for the type MockProvision
func (_mock *MockProvision) ProvisionOrgSpacePolicy() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ProvisionOrgSpacePolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvision_ProvisionOrgSpacePolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvisionOrgSpacePolicy'
type MockProvision_ProvisionOrgSpacePolicy_Call struct {
	*mock.Call
}

// ProvisionOrgSpacePolicy is a helper method to define mock.On call
func (_e *MockProvision_Expecter) ProvisionOrgSpacePolicy() *MockProvision_ProvisionOrgSpacePolicy_Call {
	return &MockProvision_ProvisionOrgSpacePolicy_Call{Call: _e.mock.On("ProvisionOrgSpacePolicy")}
}

func (_c *MockProvision_ProvisionOrgSpacePolicy_Call) Run(run func()) *MockProvision_ProvisionOrgSpacePolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvision_ProvisionOrgSpacePolicy_Call) Return(err error) *MockProvision_ProvisionOrgSpacePolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvision_ProvisionOrgSpacePolicy_Call) RunAndReturn(run func() error) *MockProvision_ProvisionOrgSpacePolicy_Call {
	_c.Call.Return(run)
	return _c
}
