// Code generated by mockery v2.26.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Provision is an autogenerated mock type for the Provision type
type Provision struct {
	mock.Mock
}

// ProvisionHostPolicy provides a mock function with given fields:
func (_m *Provision) ProvisionHostPolicy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ProvisionOrgSpacePolicy provides a mock function with given fields:
func (_m *Provision) ProvisionOrgSpacePolicy() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewProvision interface {
	mock.TestingT
	Cleanup(func())
}

// NewProvision creates a new instance of Provision. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProvision(t mockConstructorTestingTNewProvision) *Provision {
	mock := &Provision{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
