// Code generated by "stringer -type=Kind -linecomment -output kind.gen.go"; DO NOT EDIT.

package conjur

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[KindUser-0]
	_ = x[KindHost-1]
	_ = x[KindLayer-2]
	_ = x[KindGroup-3]
	_ = x[KindPolicy-4]
	_ = x[KindVariable-5]
	_ = x[KindWebservice-6]
}

const _Kind_name = "userhostlayergrouppolicyvariablewebservice"

var _Kind_index = [...]uint8{0, 4, 8, 13, 18, 24, 32, 42}

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_Kind_index)-1) {
		return "Kind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Kind_name[_Kind_index[i]:_Kind_index[i+1]]
}
