// Code generated by "enumer -type=Kind -linecomment -text -output kind.gen.go"; DO NOT EDIT.

package conjur

import (
	"fmt"
	"strings"
)

const _KindName = "userhostlayergrouppolicyvariablewebservice"

var _KindIndex = [...]uint8{0, 4, 8, 13, 18, 24, 32, 42}

const _KindLowerName = "userhostlayergrouppolicyvariablewebservice"

func (i Kind) String() string {
	if i < 0 || i >= Kind(len(_KindIndex)-1) {
		return fmt.Sprintf("Kind(%d)", i)
	}
	return _KindName[_KindIndex[i]:_KindIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _KindNoOp() {
	var x [1]struct{}
	_ = x[KindUser-(0)]
	_ = x[KindHost-(1)]
	_ = x[KindLayer-(2)]
	_ = x[KindGroup-(3)]
	_ = x[KindPolicy-(4)]
	_ = x[KindVariable-(5)]
	_ = x[KindWebservice-(6)]
}

var _KindValues = []Kind{KindUser, KindHost, KindLayer, KindGroup, KindPolicy, KindVariable, KindWebservice}

var _KindNameToValueMap = map[string]Kind{
	_KindName[0:4]:        KindUser,
	_KindLowerName[0:4]:   KindUser,
	_KindName[4:8]:        KindHost,
	_KindLowerName[4:8]:   KindHost,
	_KindName[8:13]:       KindLayer,
	_KindLowerName[8:13]:  KindLayer,
	_KindName[13:18]:      KindGroup,
	_KindLowerName[13:18]: KindGroup,
	_KindName[18:24]:      KindPolicy,
	_KindLowerName[18:24]: KindPolicy,
	_KindName[24:32]:      KindVariable,
	_KindLowerName[24:32]: KindVariable,
	_KindName[32:42]:      KindWebservice,
	_KindLowerName[32:42]: KindWebservice,
}

var _KindNames = []string{
	_KindName[0:4],
	_KindName[4:8],
	_KindName[8:13],
	_KindName[13:18],
	_KindName[18:24],
	_KindName[24:32],
	_KindName[32:42],
}

// KindString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func KindString(s string) (Kind, error) {
	if val, ok := _KindNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _KindNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Kind values", s)
}

// KindValues returns all values of the enum
func KindValues() []Kind {
	return _KindValues
}

// KindStrings returns a slice of all String values of the enum
func KindStrings() []string {
	strs := make([]string, len(_KindNames))
	copy(strs, _KindNames)
	return strs
}

// IsAKind returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Kind) IsAKind() bool {
	for _, v := range _KindValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalText implements the encoding.TextMarshaler interface for Kind
func (i Kind) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Kind
func (i *Kind) UnmarshalText(text []byte) error {
	var err error
	*i, err = KindString(string(text))
	return err
}
