// Code generated by "stringer -type=Privilege -linecomment -output priviledgestring.gen.go"; DO NOT EDIT.

package conjur

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PrivilegeRead-0]
	_ = x[PrivilegeUpdate-1]
	_ = x[PrivilegeCreate-2]
}

const _Privilege_name = "readupdatecreate"

var _Privilege_index = [...]uint8{0, 4, 10, 16}

func (i Privilege) String() string {
	if i < 0 || i >= Privilege(len(_Privilege_index)-1) {
		return "Privilege(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Privilege_name[_Privilege_index[i]:_Privilege_index[i+1]]
}
