// Code generated by "enumer -type=Privilege -linecomment -output priviledgestring.gen.go"; DO NOT EDIT.

package conjur

import (
	"fmt"
	"strings"
)

const _PrivilegeName = "readupdatecreate"

var _PrivilegeIndex = [...]uint8{0, 4, 10, 16}

const _PrivilegeLowerName = "readupdatecreate"

func (i Privilege) String() string {
	if i < 0 || i >= Privilege(len(_PrivilegeIndex)-1) {
		return fmt.Sprintf("Privilege(%d)", i)
	}
	return _PrivilegeName[_PrivilegeIndex[i]:_PrivilegeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PrivilegeNoOp() {
	var x [1]struct{}
	_ = x[PrivilegeRead-(0)]
	_ = x[PrivilegeUpdate-(1)]
	_ = x[PrivilegeCreate-(2)]
}

var _PrivilegeValues = []Privilege{PrivilegeRead, PrivilegeUpdate, PrivilegeCreate}

var _PrivilegeNameToValueMap = map[string]Privilege{
	_PrivilegeName[0:4]:        PrivilegeRead,
	_PrivilegeLowerName[0:4]:   PrivilegeRead,
	_PrivilegeName[4:10]:       PrivilegeUpdate,
	_PrivilegeLowerName[4:10]:  PrivilegeUpdate,
	_PrivilegeName[10:16]:      PrivilegeCreate,
	_PrivilegeLowerName[10:16]: PrivilegeCreate,
}

var _PrivilegeNames = []string{
	_PrivilegeName[0:4],
	_PrivilegeName[4:10],
	_PrivilegeName[10:16],
}

// PrivilegeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PrivilegeString(s string) (Privilege, error) {
	if val, ok := _PrivilegeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PrivilegeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Privilege values", s)
}

// PrivilegeValues returns all values of the enum
func PrivilegeValues() []Privilege {
	return _PrivilegeValues
}

// PrivilegeStrings returns a slice of all String values of the enum
func PrivilegeStrings() []string {
	strs := make([]string, len(_PrivilegeNames))
	copy(strs, _PrivilegeNames)
	return strs
}

// IsAPrivilege returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Privilege) IsAPrivilege() bool {
	for _, v := range _PrivilegeValues {
		if i == v {
			return true
		}
	}
	return false
}
