// Code generated by "enumer -type=VariablePrivilege -linecomment -output variablepriviledgestring.gen.go"; DO NOT EDIT.

package conjur

import (
	"fmt"
	"strings"
)

const _VariablePrivilegeName = "readexecuteupdate"

var _VariablePrivilegeIndex = [...]uint8{0, 4, 11, 17}

const _VariablePrivilegeLowerName = "readexecuteupdate"

func (i VariablePrivilege) String() string {
	if i < 0 || i >= VariablePrivilege(len(_VariablePrivilegeIndex)-1) {
		return fmt.Sprintf("VariablePrivilege(%d)", i)
	}
	return _VariablePrivilegeName[_VariablePrivilegeIndex[i]:_VariablePrivilegeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _VariablePrivilegeNoOp() {
	var x [1]struct{}
	_ = x[VariablePrivilegeRead-(0)]
	_ = x[VariablePrivilegeExecute-(1)]
	_ = x[VariablePrivilegeUpdate-(2)]
}

var _VariablePrivilegeValues = []VariablePrivilege{VariablePrivilegeRead, VariablePrivilegeExecute, VariablePrivilegeUpdate}

var _VariablePrivilegeNameToValueMap = map[string]VariablePrivilege{
	_VariablePrivilegeName[0:4]:        VariablePrivilegeRead,
	_VariablePrivilegeLowerName[0:4]:   VariablePrivilegeRead,
	_VariablePrivilegeName[4:11]:       VariablePrivilegeExecute,
	_VariablePrivilegeLowerName[4:11]:  VariablePrivilegeExecute,
	_VariablePrivilegeName[11:17]:      VariablePrivilegeUpdate,
	_VariablePrivilegeLowerName[11:17]: VariablePrivilegeUpdate,
}

var _VariablePrivilegeNames = []string{
	_VariablePrivilegeName[0:4],
	_VariablePrivilegeName[4:11],
	_VariablePrivilegeName[11:17],
}

// VariablePrivilegeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func VariablePrivilegeString(s string) (VariablePrivilege, error) {
	if val, ok := _VariablePrivilegeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _VariablePrivilegeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to VariablePrivilege values", s)
}

// VariablePrivilegeValues returns all values of the enum
func VariablePrivilegeValues() []VariablePrivilege {
	return _VariablePrivilegeValues
}

// VariablePrivilegeStrings returns a slice of all String values of the enum
func VariablePrivilegeStrings() []string {
	strs := make([]string, len(_VariablePrivilegeNames))
	copy(strs, _VariablePrivilegeNames)
	return strs
}

// IsAVariablePrivilege returns "true" if the value is listed in the enum definition. "false" otherwise
func (i VariablePrivilege) IsAVariablePrivilege() bool {
	for _, v := range _VariablePrivilegeValues {
		if i == v {
			return true
		}
	}
	return false
}
