// Code generated by "stringer -type=VariablePrivilege -linecomment"; DO NOT EDIT.

package conjur

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[VariablePrivilegeRead-0]
	_ = x[VariablePrivilegeExecute-1]
	_ = x[VariablePrivilegeUpdate-2]
}

const _VariablePrivilege_name = "readexecuteupdate"

var _VariablePrivilege_index = [...]uint8{0, 4, 11, 17}

func (i VariablePrivilege) String() string {
	if i < 0 || i >= VariablePrivilege(len(_VariablePrivilege_index)-1) {
		return "VariablePrivilege(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VariablePrivilege_name[_VariablePrivilege_index[i]:_VariablePrivilege_index[i+1]]
}
