// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/cyberark/conjur-service-broker-go/internal/servicebroker"
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockServerInterface creates a new instance of MockServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerInterface {
	mock := &MockServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServerInterface is an autogenerated mock type for the ServerInterface type
type MockServerInterface struct {
	mock.Mock
}

type MockServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerInterface) EXPECT() *MockServerInterface_Expecter {
	return &MockServerInterface_Expecter{mock: &_m.Mock}
}

// CatalogGet provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) CatalogGet(c *gin.Context, params servicebroker.CatalogGetParams) {
	_mock.Called(c, params)
	return
}

// MockServerInterface_CatalogGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CatalogGet'
type MockServerInterface_CatalogGet_Call struct {
	*mock.Call
}

// CatalogGet is a helper method to define mock.On call
//   - c *gin.Context
//   - params servicebroker.CatalogGetParams
func (_e *MockServerInterface_Expecter) CatalogGet(c interface{}, params interface{}) *MockServerInterface_CatalogGet_Call {
	return &MockServerInterface_CatalogGet_Call{Call: _e.mock.On("CatalogGet", c, params)}
}

func (_c *MockServerInterface_CatalogGet_Call) Run(run func(c *gin.Context, params servicebroker.CatalogGetParams)) *MockServerInterface_CatalogGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 servicebroker.CatalogGetParams
		if args[1] != nil {
			arg1 = args[1].(servicebroker.CatalogGetParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockServerInterface_CatalogGet_Call) Return() *MockServerInterface_CatalogGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_CatalogGet_Call) RunAndReturn(run func(c *gin.Context, params servicebroker.CatalogGetParams)) *MockServerInterface_CatalogGet_Call {
	_c.Run(run)
	return _c
}

// ServiceBindingBinding provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) ServiceBindingBinding(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingBindingParams) {
	_mock.Called(c, instanceId, bindingId, params)
	return
}

// MockServerInterface_ServiceBindingBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceBindingBinding'
type MockServerInterface_ServiceBindingBinding_Call struct {
	*mock.Call
}

// ServiceBindingBinding is a helper method to define mock.On call
//   - c *gin.Context
//   - instanceId string
//   - bindingId string
//   - params servicebroker.ServiceBindingBindingParams
func (_e *MockServerInterface_Expecter) ServiceBindingBinding(c interface{}, instanceId interface{}, bindingId interface{}, params interface{}) *MockServerInterface_ServiceBindingBinding_Call {
	return &MockServerInterface_ServiceBindingBinding_Call{Call: _e.mock.On("ServiceBindingBinding", c, instanceId, bindingId, params)}
}

func (_c *MockServerInterface_ServiceBindingBinding_Call) Run(run func(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingBindingParams)) *MockServerInterface_ServiceBindingBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 servicebroker.ServiceBindingBindingParams
		if args[3] != nil {
			arg3 = args[3].(servicebroker.ServiceBindingBindingParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServerInterface_ServiceBindingBinding_Call) Return() *MockServerInterface_ServiceBindingBinding_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_ServiceBindingBinding_Call) RunAndReturn(run func(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingBindingParams)) *MockServerInterface_ServiceBindingBinding_Call {
	_c.Run(run)
	return _c
}

// ServiceBindingGet provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) ServiceBindingGet(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingGetParams) {
	_mock.Called(c, instanceId, bindingId, params)
	return
}

// MockServerInterface_ServiceBindingGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceBindingGet'
type MockServerInterface_ServiceBindingGet_Call struct {
	*mock.Call
}

// ServiceBindingGet is a helper method to define mock.On call
//   - c *gin.Context
//   - instanceId string
//   - bindingId string
//   - params servicebroker.ServiceBindingGetParams
func (_e *MockServerInterface_Expecter) ServiceBindingGet(c interface{}, instanceId interface{}, bindingId interface{}, params interface{}) *MockServerInterface_ServiceBindingGet_Call {
	return &MockServerInterface_ServiceBindingGet_Call{Call: _e.mock.On("ServiceBindingGet", c, instanceId, bindingId, params)}
}

func (_c *MockServerInterface_ServiceBindingGet_Call) Run(run func(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingGetParams)) *MockServerInterface_ServiceBindingGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 servicebroker.ServiceBindingGetParams
		if args[3] != nil {
			arg3 = args[3].(servicebroker.ServiceBindingGetParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServerInterface_ServiceBindingGet_Call) Return() *MockServerInterface_ServiceBindingGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_ServiceBindingGet_Call) RunAndReturn(run func(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingGetParams)) *MockServerInterface_ServiceBindingGet_Call {
	_c.Run(run)
	return _c
}

// ServiceBindingLastOperationGet provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) ServiceBindingLastOperationGet(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingLastOperationGetParams) {
	_mock.Called(c, instanceId, bindingId, params)
	return
}

// MockServerInterface_ServiceBindingLastOperationGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceBindingLastOperationGet'
type MockServerInterface_ServiceBindingLastOperationGet_Call struct {
	*mock.Call
}

// ServiceBindingLastOperationGet is a helper method to define mock.On call
//   - c *gin.Context
//   - instanceId string
//   - bindingId string
//   - params servicebroker.ServiceBindingLastOperationGetParams
func (_e *MockServerInterface_Expecter) ServiceBindingLastOperationGet(c interface{}, instanceId interface{}, bindingId interface{}, params interface{}) *MockServerInterface_ServiceBindingLastOperationGet_Call {
	return &MockServerInterface_ServiceBindingLastOperationGet_Call{Call: _e.mock.On("ServiceBindingLastOperationGet", c, instanceId, bindingId, params)}
}

func (_c *MockServerInterface_ServiceBindingLastOperationGet_Call) Run(run func(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingLastOperationGetParams)) *MockServerInterface_ServiceBindingLastOperationGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 servicebroker.ServiceBindingLastOperationGetParams
		if args[3] != nil {
			arg3 = args[3].(servicebroker.ServiceBindingLastOperationGetParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServerInterface_ServiceBindingLastOperationGet_Call) Return() *MockServerInterface_ServiceBindingLastOperationGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_ServiceBindingLastOperationGet_Call) RunAndReturn(run func(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingLastOperationGetParams)) *MockServerInterface_ServiceBindingLastOperationGet_Call {
	_c.Run(run)
	return _c
}

// ServiceBindingUnbinding provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) ServiceBindingUnbinding(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingUnbindingParams) {
	_mock.Called(c, instanceId, bindingId, params)
	return
}

// MockServerInterface_ServiceBindingUnbinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceBindingUnbinding'
type MockServerInterface_ServiceBindingUnbinding_Call struct {
	*mock.Call
}

// ServiceBindingUnbinding is a helper method to define mock.On call
//   - c *gin.Context
//   - instanceId string
//   - bindingId string
//   - params servicebroker.ServiceBindingUnbindingParams
func (_e *MockServerInterface_Expecter) ServiceBindingUnbinding(c interface{}, instanceId interface{}, bindingId interface{}, params interface{}) *MockServerInterface_ServiceBindingUnbinding_Call {
	return &MockServerInterface_ServiceBindingUnbinding_Call{Call: _e.mock.On("ServiceBindingUnbinding", c, instanceId, bindingId, params)}
}

func (_c *MockServerInterface_ServiceBindingUnbinding_Call) Run(run func(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingUnbindingParams)) *MockServerInterface_ServiceBindingUnbinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 servicebroker.ServiceBindingUnbindingParams
		if args[3] != nil {
			arg3 = args[3].(servicebroker.ServiceBindingUnbindingParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockServerInterface_ServiceBindingUnbinding_Call) Return() *MockServerInterface_ServiceBindingUnbinding_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_ServiceBindingUnbinding_Call) RunAndReturn(run func(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingUnbindingParams)) *MockServerInterface_ServiceBindingUnbinding_Call {
	_c.Run(run)
	return _c
}

// ServiceInstanceDeprovision provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) ServiceInstanceDeprovision(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceDeprovisionParams) {
	_mock.Called(c, instanceId, params)
	return
}

// MockServerInterface_ServiceInstanceDeprovision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceInstanceDeprovision'
type MockServerInterface_ServiceInstanceDeprovision_Call struct {
	*mock.Call
}

// ServiceInstanceDeprovision is a helper method to define mock.On call
//   - c *gin.Context
//   - instanceId string
//   - params servicebroker.ServiceInstanceDeprovisionParams
func (_e *MockServerInterface_Expecter) ServiceInstanceDeprovision(c interface{}, instanceId interface{}, params interface{}) *MockServerInterface_ServiceInstanceDeprovision_Call {
	return &MockServerInterface_ServiceInstanceDeprovision_Call{Call: _e.mock.On("ServiceInstanceDeprovision", c, instanceId, params)}
}

func (_c *MockServerInterface_ServiceInstanceDeprovision_Call) Run(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceDeprovisionParams)) *MockServerInterface_ServiceInstanceDeprovision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 servicebroker.ServiceInstanceDeprovisionParams
		if args[2] != nil {
			arg2 = args[2].(servicebroker.ServiceInstanceDeprovisionParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerInterface_ServiceInstanceDeprovision_Call) Return() *MockServerInterface_ServiceInstanceDeprovision_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_ServiceInstanceDeprovision_Call) RunAndReturn(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceDeprovisionParams)) *MockServerInterface_ServiceInstanceDeprovision_Call {
	_c.Run(run)
	return _c
}

// ServiceInstanceGet provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) ServiceInstanceGet(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceGetParams) {
	_mock.Called(c, instanceId, params)
	return
}

// MockServerInterface_ServiceInstanceGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceInstanceGet'
type MockServerInterface_ServiceInstanceGet_Call struct {
	*mock.Call
}

// ServiceInstanceGet is a helper method to define mock.On call
//   - c *gin.Context
//   - instanceId string
//   - params servicebroker.ServiceInstanceGetParams
func (_e *MockServerInterface_Expecter) ServiceInstanceGet(c interface{}, instanceId interface{}, params interface{}) *MockServerInterface_ServiceInstanceGet_Call {
	return &MockServerInterface_ServiceInstanceGet_Call{Call: _e.mock.On("ServiceInstanceGet", c, instanceId, params)}
}

func (_c *MockServerInterface_ServiceInstanceGet_Call) Run(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceGetParams)) *MockServerInterface_ServiceInstanceGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 servicebroker.ServiceInstanceGetParams
		if args[2] != nil {
			arg2 = args[2].(servicebroker.ServiceInstanceGetParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerInterface_ServiceInstanceGet_Call) Return() *MockServerInterface_ServiceInstanceGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_ServiceInstanceGet_Call) RunAndReturn(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceGetParams)) *MockServerInterface_ServiceInstanceGet_Call {
	_c.Run(run)
	return _c
}

// ServiceInstanceLastOperationGet provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) ServiceInstanceLastOperationGet(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceLastOperationGetParams) {
	_mock.Called(c, instanceId, params)
	return
}

// MockServerInterface_ServiceInstanceLastOperationGet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceInstanceLastOperationGet'
type MockServerInterface_ServiceInstanceLastOperationGet_Call struct {
	*mock.Call
}

// ServiceInstanceLastOperationGet is a helper method to define mock.On call
//   - c *gin.Context
//   - instanceId string
//   - params servicebroker.ServiceInstanceLastOperationGetParams
func (_e *MockServerInterface_Expecter) ServiceInstanceLastOperationGet(c interface{}, instanceId interface{}, params interface{}) *MockServerInterface_ServiceInstanceLastOperationGet_Call {
	return &MockServerInterface_ServiceInstanceLastOperationGet_Call{Call: _e.mock.On("ServiceInstanceLastOperationGet", c, instanceId, params)}
}

func (_c *MockServerInterface_ServiceInstanceLastOperationGet_Call) Run(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceLastOperationGetParams)) *MockServerInterface_ServiceInstanceLastOperationGet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 servicebroker.ServiceInstanceLastOperationGetParams
		if args[2] != nil {
			arg2 = args[2].(servicebroker.ServiceInstanceLastOperationGetParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerInterface_ServiceInstanceLastOperationGet_Call) Return() *MockServerInterface_ServiceInstanceLastOperationGet_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_ServiceInstanceLastOperationGet_Call) RunAndReturn(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceLastOperationGetParams)) *MockServerInterface_ServiceInstanceLastOperationGet_Call {
	_c.Run(run)
	return _c
}

// ServiceInstanceProvision provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) ServiceInstanceProvision(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceProvisionParams) {
	_mock.Called(c, instanceId, params)
	return
}

// MockServerInterface_ServiceInstanceProvision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceInstanceProvision'
type MockServerInterface_ServiceInstanceProvision_Call struct {
	*mock.Call
}

// ServiceInstanceProvision is a helper method to define mock.On call
//   - c *gin.Context
//   - instanceId string
//   - params servicebroker.ServiceInstanceProvisionParams
func (_e *MockServerInterface_Expecter) ServiceInstanceProvision(c interface{}, instanceId interface{}, params interface{}) *MockServerInterface_ServiceInstanceProvision_Call {
	return &MockServerInterface_ServiceInstanceProvision_Call{Call: _e.mock.On("ServiceInstanceProvision", c, instanceId, params)}
}

func (_c *MockServerInterface_ServiceInstanceProvision_Call) Run(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceProvisionParams)) *MockServerInterface_ServiceInstanceProvision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 servicebroker.ServiceInstanceProvisionParams
		if args[2] != nil {
			arg2 = args[2].(servicebroker.ServiceInstanceProvisionParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerInterface_ServiceInstanceProvision_Call) Return() *MockServerInterface_ServiceInstanceProvision_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_ServiceInstanceProvision_Call) RunAndReturn(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceProvisionParams)) *MockServerInterface_ServiceInstanceProvision_Call {
	_c.Run(run)
	return _c
}

// ServiceInstanceUpdate provides a mock function for the type MockServerInterface
func (_mock *MockServerInterface) ServiceInstanceUpdate(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceUpdateParams) {
	_mock.Called(c, instanceId, params)
	return
}

// MockServerInterface_ServiceInstanceUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ServiceInstanceUpdate'
type MockServerInterface_ServiceInstanceUpdate_Call struct {
	*mock.Call
}

// ServiceInstanceUpdate is a helper method to define mock.On call
//   - c *gin.Context
//   - instanceId string
//   - params servicebroker.ServiceInstanceUpdateParams
func (_e *MockServerInterface_Expecter) ServiceInstanceUpdate(c interface{}, instanceId interface{}, params interface{}) *MockServerInterface_ServiceInstanceUpdate_Call {
	return &MockServerInterface_ServiceInstanceUpdate_Call{Call: _e.mock.On("ServiceInstanceUpdate", c, instanceId, params)}
}

func (_c *MockServerInterface_ServiceInstanceUpdate_Call) Run(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceUpdateParams)) *MockServerInterface_ServiceInstanceUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 servicebroker.ServiceInstanceUpdateParams
		if args[2] != nil {
			arg2 = args[2].(servicebroker.ServiceInstanceUpdateParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockServerInterface_ServiceInstanceUpdate_Call) Return() *MockServerInterface_ServiceInstanceUpdate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerInterface_ServiceInstanceUpdate_Call) RunAndReturn(run func(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceUpdateParams)) *MockServerInterface_ServiceInstanceUpdate_Call {
	_c.Run(run)
	return _c
}
