// Code generated by mockery v2.28.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	servicebroker "github.cyberng.com/Conjur-Enterprise/conjur-service-broker-go/internal/servicebroker"
)

// ServerInterface is an autogenerated mock type for the ServerInterface type
type ServerInterface struct {
	mock.Mock
}

// CatalogGet provides a mock function with given fields: c, params
func (_m *ServerInterface) CatalogGet(c *gin.Context, params servicebroker.CatalogGetParams) {
	_m.Called(c, params)
}

// ServiceBindingBinding provides a mock function with given fields: c, instanceId, bindingId, params
func (_m *ServerInterface) ServiceBindingBinding(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingBindingParams) {
	_m.Called(c, instanceId, bindingId, params)
}

// ServiceBindingGet provides a mock function with given fields: c, instanceId, bindingId, params
func (_m *ServerInterface) ServiceBindingGet(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingGetParams) {
	_m.Called(c, instanceId, bindingId, params)
}

// ServiceBindingLastOperationGet provides a mock function with given fields: c, instanceId, bindingId, params
func (_m *ServerInterface) ServiceBindingLastOperationGet(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingLastOperationGetParams) {
	_m.Called(c, instanceId, bindingId, params)
}

// ServiceBindingUnbinding provides a mock function with given fields: c, instanceId, bindingId, params
func (_m *ServerInterface) ServiceBindingUnbinding(c *gin.Context, instanceId string, bindingId string, params servicebroker.ServiceBindingUnbindingParams) {
	_m.Called(c, instanceId, bindingId, params)
}

// ServiceInstanceDeprovision provides a mock function with given fields: c, instanceId, params
func (_m *ServerInterface) ServiceInstanceDeprovision(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceDeprovisionParams) {
	_m.Called(c, instanceId, params)
}

// ServiceInstanceGet provides a mock function with given fields: c, instanceId, params
func (_m *ServerInterface) ServiceInstanceGet(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceGetParams) {
	_m.Called(c, instanceId, params)
}

// ServiceInstanceLastOperationGet provides a mock function with given fields: c, instanceId, params
func (_m *ServerInterface) ServiceInstanceLastOperationGet(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceLastOperationGetParams) {
	_m.Called(c, instanceId, params)
}

// ServiceInstanceProvision provides a mock function with given fields: c, instanceId, params
func (_m *ServerInterface) ServiceInstanceProvision(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceProvisionParams) {
	_m.Called(c, instanceId, params)
}

// ServiceInstanceUpdate provides a mock function with given fields: c, instanceId, params
func (_m *ServerInterface) ServiceInstanceUpdate(c *gin.Context, instanceId string, params servicebroker.ServiceInstanceUpdateParams) {
	_m.Called(c, instanceId, params)
}

type mockConstructorTestingTNewServerInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewServerInterface creates a new instance of ServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewServerInterface(t mockConstructorTestingTNewServerInterface) *ServerInterface {
	mock := &ServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
