// Code generated by mockery v2.27.1. DO NOT EDIT.

package mocks

import (
	conjurapi "github.com/cyberark/conjur-api-go/conjurapi"
	authn "github.com/cyberark/conjur-api-go/conjurapi/authn"

	http "net/http"

	io "io"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// AddSecret provides a mock function with given fields: _a0, _a1
func (_m *Client) AddSecret(_a0 string, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AddSecretRequest provides a mock function with given fields: _a0, _a1
func (_m *Client) AddSecretRequest(_a0 string, _a1 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Authenticate provides a mock function with given fields: _a0
func (_m *Client) Authenticate(_a0 authn.LoginPair) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(authn.LoginPair) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(authn.LoginPair) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(authn.LoginPair) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticateReader provides a mock function with given fields: _a0
func (_m *Client) AuthenticateReader(_a0 authn.LoginPair) (io.ReadCloser, error) {
	ret := _m.Called(_a0)

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(authn.LoginPair) (io.ReadCloser, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(authn.LoginPair) io.ReadCloser); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(authn.LoginPair) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthenticateRequest provides a mock function with given fields: _a0
func (_m *Client) AuthenticateRequest(_a0 authn.LoginPair) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(authn.LoginPair) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(authn.LoginPair) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(authn.LoginPair) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangeCurrentUserPassword provides a mock function with given fields: _a0
func (_m *Client) ChangeCurrentUserPassword(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangeUserPassword provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) ChangeUserPassword(_a0 string, _a1 string, _a2 string) ([]byte, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]byte, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []byte); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChangeUserPasswordRequest provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) ChangeUserPasswordRequest(_a0 string, _a1 string, _a2 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *http.Request); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckPermission provides a mock function with given fields: _a0, _a1
func (_m *Client) CheckPermission(_a0 string, _a1 string) (bool, error) {
	ret := _m.Called(_a0, _a1)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckPermissionForRole provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) CheckPermissionForRole(_a0 string, _a1 string, _a2 string) (bool, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (bool, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) bool); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckPermissionForRoleRequest provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) CheckPermissionForRoleRequest(_a0 string, _a1 string, _a2 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *http.Request); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CheckPermissionRequest provides a mock function with given fields: _a0, _a1
func (_m *Client) CheckPermissionRequest(_a0 string, _a1 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateHost provides a mock function with given fields: _a0, _a1
func (_m *Client) CreateHost(_a0 string, _a1 string) (conjurapi.HostFactoryHostResponse, error) {
	ret := _m.Called(_a0, _a1)

	var r0 conjurapi.HostFactoryHostResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (conjurapi.HostFactoryHostResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) conjurapi.HostFactoryHostResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(conjurapi.HostFactoryHostResponse)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateHostRequest provides a mock function with given fields: _a0, _a1
func (_m *Client) CreateHostRequest(_a0 string, _a1 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateToken provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *Client) CreateToken(_a0 string, _a1 string, _a2 []string, _a3 int) ([]conjurapi.HostFactoryTokenResponse, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	var r0 []conjurapi.HostFactoryTokenResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, []string, int) ([]conjurapi.HostFactoryTokenResponse, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(string, string, []string, int) []conjurapi.HostFactoryTokenResponse); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]conjurapi.HostFactoryTokenResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, []string, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTokenRequest provides a mock function with given fields: _a0
func (_m *Client) CreateTokenRequest(_a0 string) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteToken provides a mock function with given fields: _a0
func (_m *Client) DeleteToken(_a0 string) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTokenRequest provides a mock function with given fields: _a0
func (_m *Client) DeleteTokenRequest(_a0 string) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ForceRefreshToken provides a mock function with given fields:
func (_m *Client) ForceRefreshToken() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAuthenticator provides a mock function with given fields:
func (_m *Client) GetAuthenticator() conjurapi.Authenticator {
	ret := _m.Called()

	var r0 conjurapi.Authenticator
	if rf, ok := ret.Get(0).(func() conjurapi.Authenticator); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(conjurapi.Authenticator)
		}
	}

	return r0
}

// GetConfig provides a mock function with given fields:
func (_m *Client) GetConfig() conjurapi.Config {
	ret := _m.Called()

	var r0 conjurapi.Config
	if rf, ok := ret.Get(0).(func() conjurapi.Config); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(conjurapi.Config)
	}

	return r0
}

// GetHttpClient provides a mock function with given fields:
func (_m *Client) GetHttpClient() *http.Client {
	ret := _m.Called()

	var r0 *http.Client
	if rf, ok := ret.Get(0).(func() *http.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Client)
		}
	}

	return r0
}

// InternalAuthenticate provides a mock function with given fields:
func (_m *Client) InternalAuthenticate() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOidcProviders provides a mock function with given fields:
func (_m *Client) ListOidcProviders() ([]conjurapi.OidcProvider, error) {
	ret := _m.Called()

	var r0 []conjurapi.OidcProvider
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]conjurapi.OidcProvider, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []conjurapi.OidcProvider); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]conjurapi.OidcProvider)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListOidcProvidersRequest provides a mock function with given fields:
func (_m *Client) ListOidcProvidersRequest() (*http.Request, error) {
	ret := _m.Called()

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func() (*http.Request, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *http.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadPolicy provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) LoadPolicy(_a0 conjurapi.PolicyMode, _a1 string, _a2 io.Reader) (*conjurapi.PolicyResponse, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *conjurapi.PolicyResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(conjurapi.PolicyMode, string, io.Reader) (*conjurapi.PolicyResponse, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(conjurapi.PolicyMode, string, io.Reader) *conjurapi.PolicyResponse); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*conjurapi.PolicyResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(conjurapi.PolicyMode, string, io.Reader) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadPolicyRequest provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) LoadPolicyRequest(_a0 conjurapi.PolicyMode, _a1 string, _a2 io.Reader) (*http.Request, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(conjurapi.PolicyMode, string, io.Reader) (*http.Request, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(conjurapi.PolicyMode, string, io.Reader) *http.Request); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(conjurapi.PolicyMode, string, io.Reader) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: _a0, _a1
func (_m *Client) Login(_a0 string, _a1 string) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoginRequest provides a mock function with given fields: _a0, _a1
func (_m *Client) LoginRequest(_a0 string, _a1 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NeedsTokenRefresh provides a mock function with given fields:
func (_m *Client) NeedsTokenRefresh() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OidcAuthenticate provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) OidcAuthenticate(_a0 string, _a1 string, _a2 string) ([]byte, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) ([]byte, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) []byte); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OidcAuthenticateRequest provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) OidcAuthenticateRequest(_a0 string, _a1 string, _a2 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(string, string, string) *http.Request); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PermittedRoles provides a mock function with given fields: _a0, _a1
func (_m *Client) PermittedRoles(_a0 string, _a1 string) ([]string, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) []string); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PermittedRolesRequest provides a mock function with given fields: _a0, _a1
func (_m *Client) PermittedRolesRequest(_a0 string, _a1 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublicKeys provides a mock function with given fields: _a0, _a1
func (_m *Client) PublicKeys(_a0 string, _a1 string) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) ([]byte, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PublicKeysRequest provides a mock function with given fields: _a0, _a1
func (_m *Client) PublicKeysRequest(_a0 string, _a1 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PurgeCredentials provides a mock function with given fields:
func (_m *Client) PurgeCredentials() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RefreshToken provides a mock function with given fields:
func (_m *Client) RefreshToken() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Resource provides a mock function with given fields: _a0
func (_m *Client) Resource(_a0 string) (map[string]interface{}, error) {
	ret := _m.Called(_a0)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceExists provides a mock function with given fields: _a0
func (_m *Client) ResourceExists(_a0 string) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceIDs provides a mock function with given fields: _a0
func (_m *Client) ResourceIDs(_a0 *conjurapi.ResourceFilter) ([]string, error) {
	ret := _m.Called(_a0)

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func(*conjurapi.ResourceFilter) ([]string, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*conjurapi.ResourceFilter) []string); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func(*conjurapi.ResourceFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceRequest provides a mock function with given fields: _a0
func (_m *Client) ResourceRequest(_a0 string) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Resources provides a mock function with given fields: _a0
func (_m *Client) Resources(_a0 *conjurapi.ResourceFilter) ([]map[string]interface{}, error) {
	ret := _m.Called(_a0)

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(*conjurapi.ResourceFilter) ([]map[string]interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*conjurapi.ResourceFilter) []map[string]interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*conjurapi.ResourceFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourcesRequest provides a mock function with given fields: _a0
func (_m *Client) ResourcesRequest(_a0 *conjurapi.ResourceFilter) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(*conjurapi.ResourceFilter) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*conjurapi.ResourceFilter) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(*conjurapi.ResourceFilter) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveBatchSecrets provides a mock function with given fields: _a0
func (_m *Client) RetrieveBatchSecrets(_a0 []string) (map[string][]byte, error) {
	ret := _m.Called(_a0)

	var r0 map[string][]byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (map[string][]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]string) map[string][]byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveBatchSecretsRequest provides a mock function with given fields: _a0, _a1
func (_m *Client) RetrieveBatchSecretsRequest(_a0 []string, _a1 bool) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func([]string, bool) (*http.Request, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func([]string, bool) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func([]string, bool) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveBatchSecretsSafe provides a mock function with given fields: _a0
func (_m *Client) RetrieveBatchSecretsSafe(_a0 []string) (map[string][]byte, error) {
	ret := _m.Called(_a0)

	var r0 map[string][]byte
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) (map[string][]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]string) map[string][]byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]byte)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveSecret provides a mock function with given fields: _a0
func (_m *Client) RetrieveSecret(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveSecretReader provides a mock function with given fields: _a0
func (_m *Client) RetrieveSecretReader(_a0 string) (io.ReadCloser, error) {
	ret := _m.Called(_a0)

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (io.ReadCloser, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) io.ReadCloser); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveSecretRequest provides a mock function with given fields: _a0
func (_m *Client) RetrieveSecretRequest(_a0 string) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveSecretWithVersion provides a mock function with given fields: _a0, _a1
func (_m *Client) RetrieveSecretWithVersion(_a0 string, _a1 int) ([]byte, error) {
	ret := _m.Called(_a0, _a1)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) ([]byte, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, int) []byte); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveSecretWithVersionReader provides a mock function with given fields: _a0, _a1
func (_m *Client) RetrieveSecretWithVersionReader(_a0 string, _a1 int) (io.ReadCloser, error) {
	ret := _m.Called(_a0, _a1)

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (io.ReadCloser, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, int) io.ReadCloser); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RetrieveSecretWithVersionRequest provides a mock function with given fields: _a0, _a1
func (_m *Client) RetrieveSecretWithVersionRequest(_a0 string, _a1 int) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int) (*http.Request, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, int) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Role provides a mock function with given fields: _a0
func (_m *Client) Role(_a0 string) (map[string]interface{}, error) {
	ret := _m.Called(_a0)

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleExists provides a mock function with given fields: _a0
func (_m *Client) RoleExists(_a0 string) (bool, error) {
	ret := _m.Called(_a0)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleMembers provides a mock function with given fields: _a0
func (_m *Client) RoleMembers(_a0 string) ([]map[string]interface{}, error) {
	ret := _m.Called(_a0)

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]map[string]interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []map[string]interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleMembersRequest provides a mock function with given fields: _a0
func (_m *Client) RoleMembersRequest(_a0 string) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleMemberships provides a mock function with given fields: _a0
func (_m *Client) RoleMemberships(_a0 string) ([]map[string]interface{}, error) {
	ret := _m.Called(_a0)

	var r0 []map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]map[string]interface{}, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []map[string]interface{}); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleMembershipsRequest provides a mock function with given fields: _a0
func (_m *Client) RoleMembershipsRequest(_a0 string) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RoleRequest provides a mock function with given fields: _a0
func (_m *Client) RoleRequest(_a0 string) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RotateAPIKey provides a mock function with given fields: _a0
func (_m *Client) RotateAPIKey(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RotateAPIKeyReader provides a mock function with given fields: _a0
func (_m *Client) RotateAPIKeyReader(_a0 string) (io.ReadCloser, error) {
	ret := _m.Called(_a0)

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (io.ReadCloser, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) io.ReadCloser); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RotateAPIKeyRequest provides a mock function with given fields: _a0
func (_m *Client) RotateAPIKeyRequest(_a0 string) (*http.Request, error) {
	ret := _m.Called(_a0)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*http.Request, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *http.Request); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RotateCurrentUserAPIKey provides a mock function with given fields:
func (_m *Client) RotateCurrentUserAPIKey() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RotateCurrentUserAPIKeyRequest provides a mock function with given fields: _a0, _a1
func (_m *Client) RotateCurrentUserAPIKeyRequest(_a0 string, _a1 string) (*http.Request, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*http.Request, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, string) *http.Request); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RotateHostAPIKey provides a mock function with given fields: _a0
func (_m *Client) RotateHostAPIKey(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RotateUserAPIKey provides a mock function with given fields: _a0
func (_m *Client) RotateUserAPIKey(_a0 string) ([]byte, error) {
	ret := _m.Called(_a0)

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetAuthenticator provides a mock function with given fields: _a0
func (_m *Client) SetAuthenticator(_a0 conjurapi.Authenticator) {
	_m.Called(_a0)
}

// SetHttpClient provides a mock function with given fields: _a0
func (_m *Client) SetHttpClient(_a0 *http.Client) {
	_m.Called(_a0)
}

// SubmitRequest provides a mock function with given fields: _a0
func (_m *Client) SubmitRequest(_a0 *http.Request) (*http.Response, error) {
	ret := _m.Called(_a0)

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(*http.Request) (*http.Response, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WhoAmI provides a mock function with given fields:
func (_m *Client) WhoAmI() ([]byte, error) {
	ret := _m.Called()

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WhoAmIRequest provides a mock function with given fields:
func (_m *Client) WhoAmIRequest() (*http.Request, error) {
	ret := _m.Called()

	var r0 *http.Request
	var r1 error
	if rf, ok := ret.Get(0).(func() (*http.Request, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *http.Request); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Request)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewClient(t mockConstructorTestingTNewClient) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
