ARG BASE_IMAGE_VERSION=1.24-alpine

FROM golang:${BASE_IMAGE_VERSION}

RUN apk add --no-cache bash

RUN go install github.com/jstemmer/go-junit-report/v2@v2.0.0 && go install github.com/boumenot/gocover-cobertura@v1.2.0

WORKDIR /src
COPY go.* .
COPY . .

CMD ./scripts/test.sh
