ARG BASE_IMAGE_VERSION=1.24-alpine

FROM golang:${BASE_IMAGE_VERSION}

RUN apk add curl && \
    curl --location --silent "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | \
    tar -zx -C /usr/local/bin

WORKDIR /opt/e2e

COPY go.* .

COPY . .

CMD ["go", "test", "--timeout", "30m"]
