ARG BASE_IMAGE_VERSION=1.24-alpine

FROM golang:${BASE_IMAGE_VERSION}

RUN apk add curl && \
    curl --location --silent "https://packages.cloudfoundry.org/stable?release=linux64-binary&version=v8&source=github" | \
    tar -zx -C /usr/local/bin

WORKDIR /opt/e2e

# On CyberArk dev laptops, golang dependencies are downloaded
# with a corporate proxy in the middle. For these connections
# succeed we need to configure the proxy CA certificate in the
# build container.
#
# To also allow this script to work on non-CyberArk laptops
# we copy the certificate into the Docker image as a (potentially
# empty) directory, rather than rely on the CA file itself.
COPY build_ca_certificate/ /usr/local/share/ca-certificates/
RUN update-ca-certificates

COPY go.* .

COPY . .

CMD ["go", "test", "--timeout", "30m"]
