// Package servicebroker provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package servicebroker

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
)

// Defines values for LastOperationResourceState.
const (
	Failed     LastOperationResourceState = "failed"
	InProgress LastOperationResourceState = "in progress"
	Succeeded  LastOperationResourceState = "succeeded"
)

// Defines values for ServiceRequires.
const (
	RouteForwarding ServiceRequires = "route_forwarding"
	SyslogDrain     ServiceRequires = "syslog_drain"
	VolumeMount     ServiceRequires = "volume_mount"
)

// Defines values for ServiceBindingEndpointProtocol.
const (
	All ServiceBindingEndpointProtocol = "all"
	Tcp ServiceBindingEndpointProtocol = "tcp"
	Udp ServiceBindingEndpointProtocol = "udp"
)

// Defines values for ServiceBindingVolumeMountDeviceType.
const (
	Shared ServiceBindingVolumeMountDeviceType = "shared"
)

// Defines values for ServiceBindingVolumeMountMode.
const (
	R  ServiceBindingVolumeMountMode = "r"
	Rw ServiceBindingVolumeMountMode = "rw"
)

// AsyncOperation defines model for AsyncOperation.
type AsyncOperation struct {
	Operation *string `json:"operation,omitempty"`
}

// Catalog defines model for Catalog.
type Catalog struct {
	Services *[]Service `json:"services,omitempty"`
}

// Context See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details.
type Context = map[string]interface{}

// DashboardClient defines model for DashboardClient.
type DashboardClient struct {
	Id          *string `json:"id,omitempty"`
	RedirectUri *string `json:"redirect_uri,omitempty"`
	Secret      *string `json:"secret,omitempty"`
}

// Error See [Service Broker Errors](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#service-broker-errors) for more details.
type Error struct {
	Description      *string `json:"description,omitempty"`
	Error            *string `json:"error,omitempty"`
	InstanceUsable   *bool   `json:"instance_usable,omitempty"`
	UpdateRepeatable *bool   `json:"update_repeatable,omitempty"`
}

// LastOperationResource defines model for LastOperationResource.
type LastOperationResource struct {
	Description      *string                    `json:"description,omitempty"`
	InstanceUsable   *bool                      `json:"instance_usable,omitempty"`
	State            LastOperationResourceState `json:"state"`
	UpdateRepeatable *bool                      `json:"update_repeatable,omitempty"`
}

// LastOperationResourceState defines model for LastOperationResource.State.
type LastOperationResourceState string

// MaintenanceInfo defines model for MaintenanceInfo.
type MaintenanceInfo struct {
	Description *string `json:"description,omitempty"`
	Version     string  `json:"version"`
}

// Metadata See [Service Metadata Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata) for more details.
type Metadata = map[string]interface{}

// Object defines model for Object.
type Object = map[string]interface{}

// Plan defines model for Plan.
type Plan struct {
	Bindable               *bool            `json:"bindable,omitempty"`
	BindingRotatable       *bool            `json:"binding_rotatable,omitempty"`
	Description            string           `json:"description"`
	Free                   *bool            `json:"free,omitempty"`
	Id                     string           `json:"id"`
	MaintenanceInfo        *MaintenanceInfo `json:"maintenance_info,omitempty"`
	MaximumPollingDuration *int             `json:"maximum_polling_duration,omitempty"`

	// Metadata See [Service Metadata Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata) for more details.
	Metadata       *Metadata `json:"metadata,omitempty"`
	Name           string    `json:"name"`
	PlanUpdateable *bool     `json:"plan_updateable,omitempty"`
	Schemas        *Schemas  `json:"schemas,omitempty"`
}

// Schemas defines model for Schemas.
type Schemas struct {
	ServiceBinding  *ServiceBindingSchema  `json:"service_binding,omitempty"`
	ServiceInstance *ServiceInstanceSchema `json:"service_instance,omitempty"`
}

// Service defines model for Service.
type Service struct {
	Bindable         bool             `json:"bindable"`
	BindingRotatable *bool            `json:"binding_rotatable,omitempty"`
	DashboardClient  *DashboardClient `json:"dashboard_client,omitempty"`
	Description      string           `json:"description"`
	Id               string           `json:"id"`

	// Metadata See [Service Metadata Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#service-metadata) for more details.
	Metadata       *Metadata          `json:"metadata,omitempty"`
	Name           string             `json:"name"`
	PlanUpdateable *bool              `json:"plan_updateable,omitempty"`
	Plans          []Plan             `json:"plans"`
	Requires       *[]ServiceRequires `json:"requires,omitempty"`
	Tags           *[]string          `json:"tags,omitempty"`
}

// ServiceRequires defines model for Service.Requires.
type ServiceRequires string

// ServiceBindingEndpoint defines model for ServiceBindingEndpoint.
type ServiceBindingEndpoint struct {
	Host     string                          `json:"host"`
	Ports    []string                        `json:"ports"`
	Protocol *ServiceBindingEndpointProtocol `json:"protocol,omitempty"`
}

// ServiceBindingEndpointProtocol defines model for ServiceBindingEndpoint.Protocol.
type ServiceBindingEndpointProtocol string

// ServiceBindingMetadata defines model for ServiceBindingMetadata.
type ServiceBindingMetadata struct {
	ExpiresAt   *string `json:"expires_at,omitempty"`
	RenewBefore *string `json:"renew_before,omitempty"`
}

// ServiceBindingRequest defines model for ServiceBindingRequest.
type ServiceBindingRequest struct {
	AppGuid      *string                      `json:"app_guid,omitempty"`
	BindResource *ServiceBindingResouceObject `json:"bind_resource,omitempty"`

	// Context See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details.
	Context              *Context `json:"context,omitempty"`
	Parameters           *Object  `json:"parameters,omitempty"`
	PlanId               string   `json:"plan_id"`
	PredecessorBindingId *string  `json:"predecessor_binding_id,omitempty"`
	ServiceId            string   `json:"service_id"`
}

// ServiceBindingResouceObject defines model for ServiceBindingResouceObject.
type ServiceBindingResouceObject struct {
	AppGuid *string `json:"app_guid,omitempty"`
	Route   *string `json:"route,omitempty"`
}

// ServiceBindingResource defines model for ServiceBindingResource.
type ServiceBindingResource struct {
	Credentials     *Object                      `json:"credentials,omitempty"`
	Endpoints       *[]ServiceBindingEndpoint    `json:"endpoints,omitempty"`
	Metadata        *ServiceBindingMetadata      `json:"metadata,omitempty"`
	Parameters      *Object                      `json:"parameters,omitempty"`
	RouteServiceUrl *string                      `json:"route_service_url,omitempty"`
	SyslogDrainUrl  *string                      `json:"syslog_drain_url,omitempty"`
	VolumeMounts    *[]ServiceBindingVolumeMount `json:"volume_mounts,omitempty"`
}

// ServiceBindingResponse defines model for ServiceBindingResponse.
type ServiceBindingResponse struct {
	Credentials     *Object                      `json:"credentials,omitempty"`
	Endpoints       *[]ServiceBindingEndpoint    `json:"endpoints,omitempty"`
	Metadata        *ServiceBindingMetadata      `json:"metadata,omitempty"`
	RouteServiceUrl *string                      `json:"route_service_url,omitempty"`
	SyslogDrainUrl  *string                      `json:"syslog_drain_url,omitempty"`
	VolumeMounts    *[]ServiceBindingVolumeMount `json:"volume_mounts,omitempty"`
}

// ServiceBindingSchema defines model for ServiceBindingSchema.
type ServiceBindingSchema struct {
	Create *struct {
		Parameters *map[string]interface{} `json:"parameters,omitempty"`
	} `json:"create,omitempty"`
}

// ServiceBindingVolumeMount defines model for ServiceBindingVolumeMount.
type ServiceBindingVolumeMount struct {
	ContainerDir string                              `json:"container_dir"`
	Device       ServiceBindingVolumeMountDevice     `json:"device"`
	DeviceType   ServiceBindingVolumeMountDeviceType `json:"device_type"`
	Driver       string                              `json:"driver"`
	Mode         ServiceBindingVolumeMountMode       `json:"mode"`
}

// ServiceBindingVolumeMountDeviceType defines model for ServiceBindingVolumeMount.DeviceType.
type ServiceBindingVolumeMountDeviceType string

// ServiceBindingVolumeMountMode defines model for ServiceBindingVolumeMount.Mode.
type ServiceBindingVolumeMountMode string

// ServiceBindingVolumeMountDevice defines model for ServiceBindingVolumeMountDevice.
type ServiceBindingVolumeMountDevice struct {
	MountConfig *Object `json:"mount_config,omitempty"`
	VolumeId    string  `json:"volume_id"`
}

// ServiceInstanceAsyncOperation defines model for ServiceInstanceAsyncOperation.
type ServiceInstanceAsyncOperation struct {
	DashboardUrl *string                  `json:"dashboard_url,omitempty"`
	Metadata     *ServiceInstanceMetadata `json:"metadata,omitempty"`
	Operation    *string                  `json:"operation,omitempty"`
}

// ServiceInstanceMetadata defines model for ServiceInstanceMetadata.
type ServiceInstanceMetadata struct {
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	Labels     *map[string]interface{} `json:"labels,omitempty"`
}

// ServiceInstancePreviousValues defines model for ServiceInstancePreviousValues.
type ServiceInstancePreviousValues struct {
	OrganizationId *string `json:"organization_id,omitempty"`
	PlanId         *string `json:"plan_id,omitempty"`
	ServiceId      *string `json:"service_id,omitempty"`
	SpaceId        *string `json:"space_id,omitempty"`
}

// ServiceInstanceProvisionRequestBody defines model for ServiceInstanceProvisionRequestBody.
type ServiceInstanceProvisionRequestBody struct {
	// Context See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details.
	Context          *Context `json:"context,omitempty"`
	OrganizationGuid string   `json:"organization_guid"`
	Parameters       *Object  `json:"parameters,omitempty"`
	PlanId           string   `json:"plan_id"`
	ServiceId        string   `json:"service_id"`
	SpaceGuid        string   `json:"space_guid"`
}

// ServiceInstanceProvisionResponse defines model for ServiceInstanceProvisionResponse.
type ServiceInstanceProvisionResponse struct {
	DashboardUrl *string                  `json:"dashboard_url,omitempty"`
	Metadata     *ServiceInstanceMetadata `json:"metadata,omitempty"`
}

// ServiceInstanceResource defines model for ServiceInstanceResource.
type ServiceInstanceResource struct {
	DashboardUrl    *string                  `json:"dashboard_url,omitempty"`
	MaintenanceInfo *MaintenanceInfo         `json:"maintenance_info,omitempty"`
	Metadata        *ServiceInstanceMetadata `json:"metadata,omitempty"`
	Parameters      *Object                  `json:"parameters,omitempty"`
	PlanId          *string                  `json:"plan_id,omitempty"`
	ServiceId       *string                  `json:"service_id,omitempty"`
}

// ServiceInstanceSchema defines model for ServiceInstanceSchema.
type ServiceInstanceSchema struct {
	Create *struct {
		Parameters *map[string]interface{} `json:"parameters,omitempty"`
	} `json:"create,omitempty"`
	Update *struct {
		Parameters *map[string]interface{} `json:"parameters,omitempty"`
	} `json:"update,omitempty"`
}

// ServiceInstanceUpdateRequestBody defines model for ServiceInstanceUpdateRequestBody.
type ServiceInstanceUpdateRequestBody struct {
	// Context See [Context Conventions](https://github.com/openservicebrokerapi/servicebroker/blob/master/profile.md#context-object) for more details.
	Context        *Context                       `json:"context,omitempty"`
	Parameters     *Object                        `json:"parameters,omitempty"`
	PlanId         *string                        `json:"plan_id,omitempty"`
	PreviousValues *ServiceInstancePreviousValues `json:"previous_values,omitempty"`
	ServiceId      string                         `json:"service_id"`
}

// APIVersion defines model for APIVersion.
type APIVersion = string

// OriginatingIdentity defines model for OriginatingIdentity.
type OriginatingIdentity = string

// CatalogGetParams defines parameters for CatalogGet.
type CatalogGetParams struct {
	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`
}

// ServiceInstanceDeprovisionParams defines parameters for ServiceInstanceDeprovision.
type ServiceInstanceDeprovisionParams struct {
	// ServiceId id of the service associated with the instance being deleted
	ServiceId string `form:"service_id" json:"service_id"`

	// PlanId id of the plan associated with the instance being deleted
	PlanId string `form:"plan_id" json:"plan_id"`

	// AcceptsIncomplete asynchronous deprovision supported
	AcceptsIncomplete *bool `form:"accepts_incomplete,omitempty" json:"accepts_incomplete,omitempty"`

	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`

	// XBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
	XBrokerAPIOriginatingIdentity *OriginatingIdentity `json:"X-Broker-API-Originating-Identity,omitempty"`
}

// ServiceInstanceGetParams defines parameters for ServiceInstanceGet.
type ServiceInstanceGetParams struct {
	// ServiceId id of the service associated with the instance
	ServiceId *string `form:"service_id,omitempty" json:"service_id,omitempty"`

	// PlanId id of the plan associated with the instance
	PlanId *string `form:"plan_id,omitempty" json:"plan_id,omitempty"`

	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`

	// XBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
	XBrokerAPIOriginatingIdentity *OriginatingIdentity `json:"X-Broker-API-Originating-Identity,omitempty"`
}

// ServiceInstanceUpdateParams defines parameters for ServiceInstanceUpdate.
type ServiceInstanceUpdateParams struct {
	// AcceptsIncomplete asynchronous operations supported
	AcceptsIncomplete *bool `form:"accepts_incomplete,omitempty" json:"accepts_incomplete,omitempty"`

	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`

	// XBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
	XBrokerAPIOriginatingIdentity *OriginatingIdentity `json:"X-Broker-API-Originating-Identity,omitempty"`
}

// ServiceInstanceProvisionParams defines parameters for ServiceInstanceProvision.
type ServiceInstanceProvisionParams struct {
	// AcceptsIncomplete asynchronous operations supported
	AcceptsIncomplete *bool `form:"accepts_incomplete,omitempty" json:"accepts_incomplete,omitempty"`

	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`

	// XBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
	XBrokerAPIOriginatingIdentity *OriginatingIdentity `json:"X-Broker-API-Originating-Identity,omitempty"`
}

// ServiceInstanceLastOperationGetParams defines parameters for ServiceInstanceLastOperationGet.
type ServiceInstanceLastOperationGetParams struct {
	// ServiceId id of the service associated with the instance
	ServiceId *string `form:"service_id,omitempty" json:"service_id,omitempty"`

	// PlanId id of the plan associated with the instance
	PlanId *string `form:"plan_id,omitempty" json:"plan_id,omitempty"`

	// Operation a provided identifier for the operation
	Operation *string `form:"operation,omitempty" json:"operation,omitempty"`

	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`
}

// ServiceBindingUnbindingParams defines parameters for ServiceBindingUnbinding.
type ServiceBindingUnbindingParams struct {
	// ServiceId id of the service associated with the instance for which a binding is being deleted
	ServiceId string `form:"service_id" json:"service_id"`

	// PlanId id of the plan associated with the instance for which a binding is being deleted
	PlanId string `form:"plan_id" json:"plan_id"`

	// AcceptsIncomplete asynchronous operations supported
	AcceptsIncomplete *bool `form:"accepts_incomplete,omitempty" json:"accepts_incomplete,omitempty"`

	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`

	// XBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
	XBrokerAPIOriginatingIdentity *OriginatingIdentity `json:"X-Broker-API-Originating-Identity,omitempty"`
}

// ServiceBindingGetParams defines parameters for ServiceBindingGet.
type ServiceBindingGetParams struct {
	// ServiceId id of the service associated with the instance
	ServiceId *string `form:"service_id,omitempty" json:"service_id,omitempty"`

	// PlanId id of the plan associated with the instance
	PlanId *string `form:"plan_id,omitempty" json:"plan_id,omitempty"`

	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`

	// XBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
	XBrokerAPIOriginatingIdentity *OriginatingIdentity `json:"X-Broker-API-Originating-Identity,omitempty"`
}

// ServiceBindingBindingParams defines parameters for ServiceBindingBinding.
type ServiceBindingBindingParams struct {
	// AcceptsIncomplete asynchronous operations supported
	AcceptsIncomplete *bool `form:"accepts_incomplete,omitempty" json:"accepts_incomplete,omitempty"`

	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`

	// XBrokerAPIOriginatingIdentity identity of the user that initiated the request from the Platform
	XBrokerAPIOriginatingIdentity *OriginatingIdentity `json:"X-Broker-API-Originating-Identity,omitempty"`
}

// ServiceBindingLastOperationGetParams defines parameters for ServiceBindingLastOperationGet.
type ServiceBindingLastOperationGetParams struct {
	// ServiceId id of the service associated with the instance
	ServiceId *string `form:"service_id,omitempty" json:"service_id,omitempty"`

	// PlanId id of the plan associated with the instance
	PlanId *string `form:"plan_id,omitempty" json:"plan_id,omitempty"`

	// Operation a provided identifier for the operation
	Operation *string `form:"operation,omitempty" json:"operation,omitempty"`

	// XBrokerAPIVersion version number of the Service Broker API that the Platform will use
	XBrokerAPIVersion APIVersion `json:"X-Broker-API-Version"`
}

// ServiceInstanceUpdateJSONRequestBody defines body for ServiceInstanceUpdate for application/json ContentType.
type ServiceInstanceUpdateJSONRequestBody = ServiceInstanceUpdateRequestBody

// ServiceInstanceProvisionJSONRequestBody defines body for ServiceInstanceProvision for application/json ContentType.
type ServiceInstanceProvisionJSONRequestBody = ServiceInstanceProvisionRequestBody

// ServiceBindingBindingJSONRequestBody defines body for ServiceBindingBinding for application/json ContentType.
type ServiceBindingBindingJSONRequestBody = ServiceBindingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// get the catalog of services that the service broker offers
	// (GET /v2/catalog)
	CatalogGet(c *gin.Context, params CatalogGetParams)
	// deprovision a service instance
	// (DELETE /v2/service_instances/{instance_id})
	ServiceInstanceDeprovision(c *gin.Context, instanceId string, params ServiceInstanceDeprovisionParams)
	// get a service instance
	// (GET /v2/service_instances/{instance_id})
	ServiceInstanceGet(c *gin.Context, instanceId string, params ServiceInstanceGetParams)
	// update a service instance
	// (PATCH /v2/service_instances/{instance_id})
	ServiceInstanceUpdate(c *gin.Context, instanceId string, params ServiceInstanceUpdateParams)
	// provision a service instance
	// (PUT /v2/service_instances/{instance_id})
	ServiceInstanceProvision(c *gin.Context, instanceId string, params ServiceInstanceProvisionParams)
	// get the last requested operation state for service instance
	// (GET /v2/service_instances/{instance_id}/last_operation)
	ServiceInstanceLastOperationGet(c *gin.Context, instanceId string, params ServiceInstanceLastOperationGetParams)
	// deprovision a service binding
	// (DELETE /v2/service_instances/{instance_id}/service_bindings/{binding_id})
	ServiceBindingUnbinding(c *gin.Context, instanceId string, bindingId string, params ServiceBindingUnbindingParams)
	// get a service binding
	// (GET /v2/service_instances/{instance_id}/service_bindings/{binding_id})
	ServiceBindingGet(c *gin.Context, instanceId string, bindingId string, params ServiceBindingGetParams)
	// generate a service binding
	// (PUT /v2/service_instances/{instance_id}/service_bindings/{binding_id})
	ServiceBindingBinding(c *gin.Context, instanceId string, bindingId string, params ServiceBindingBindingParams)
	// get the last requested operation state for service binding
	// (GET /v2/service_instances/{instance_id}/service_bindings/{binding_id}/last_operation)
	ServiceBindingLastOperationGet(c *gin.Context, instanceId string, bindingId string, params ServiceBindingLastOperationGetParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// CatalogGet operation middleware
func (siw *ServerInterfaceWrapper) CatalogGet(c *gin.Context) {

	var err error

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params CatalogGetParams

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.CatalogGet(c, params)
}

// ServiceInstanceDeprovision operation middleware
func (siw *ServerInterfaceWrapper) ServiceInstanceDeprovision(c *gin.Context) {

	var err error

	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameter("simple", false, "instance_id", c.Param("instance_id"), &instanceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceInstanceDeprovisionParams

	// ------------- Required query parameter "service_id" -------------

	if paramValue := c.Query("service_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument service_id is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "service_id", c.Request.URL.Query(), &params.ServiceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "plan_id" -------------

	if paramValue := c.Query("plan_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument plan_id is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "plan_id", c.Request.URL.Query(), &params.PlanId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter plan_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "accepts_incomplete" -------------

	err = runtime.BindQueryParameter("form", true, false, "accepts_incomplete", c.Request.URL.Query(), &params.AcceptsIncomplete)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accepts_incomplete: %s", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional header parameter "X-Broker-API-Originating-Identity" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Originating-Identity")]; found {
		var XBrokerAPIOriginatingIdentity OriginatingIdentity
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Originating-Identity, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Originating-Identity", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIOriginatingIdentity)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Originating-Identity: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIOriginatingIdentity = &XBrokerAPIOriginatingIdentity

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ServiceInstanceDeprovision(c, instanceId, params)
}

// ServiceInstanceGet operation middleware
func (siw *ServerInterfaceWrapper) ServiceInstanceGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameter("simple", false, "instance_id", c.Param("instance_id"), &instanceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceInstanceGetParams

	// ------------- Optional query parameter "service_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "service_id", c.Request.URL.Query(), &params.ServiceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "plan_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "plan_id", c.Request.URL.Query(), &params.PlanId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter plan_id: %s", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional header parameter "X-Broker-API-Originating-Identity" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Originating-Identity")]; found {
		var XBrokerAPIOriginatingIdentity OriginatingIdentity
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Originating-Identity, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Originating-Identity", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIOriginatingIdentity)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Originating-Identity: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIOriginatingIdentity = &XBrokerAPIOriginatingIdentity

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ServiceInstanceGet(c, instanceId, params)
}

// ServiceInstanceUpdate operation middleware
func (siw *ServerInterfaceWrapper) ServiceInstanceUpdate(c *gin.Context) {

	var err error

	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameter("simple", false, "instance_id", c.Param("instance_id"), &instanceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceInstanceUpdateParams

	// ------------- Optional query parameter "accepts_incomplete" -------------

	err = runtime.BindQueryParameter("form", true, false, "accepts_incomplete", c.Request.URL.Query(), &params.AcceptsIncomplete)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accepts_incomplete: %s", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional header parameter "X-Broker-API-Originating-Identity" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Originating-Identity")]; found {
		var XBrokerAPIOriginatingIdentity OriginatingIdentity
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Originating-Identity, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Originating-Identity", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIOriginatingIdentity)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Originating-Identity: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIOriginatingIdentity = &XBrokerAPIOriginatingIdentity

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ServiceInstanceUpdate(c, instanceId, params)
}

// ServiceInstanceProvision operation middleware
func (siw *ServerInterfaceWrapper) ServiceInstanceProvision(c *gin.Context) {

	var err error

	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameter("simple", false, "instance_id", c.Param("instance_id"), &instanceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceInstanceProvisionParams

	// ------------- Optional query parameter "accepts_incomplete" -------------

	err = runtime.BindQueryParameter("form", true, false, "accepts_incomplete", c.Request.URL.Query(), &params.AcceptsIncomplete)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accepts_incomplete: %s", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional header parameter "X-Broker-API-Originating-Identity" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Originating-Identity")]; found {
		var XBrokerAPIOriginatingIdentity OriginatingIdentity
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Originating-Identity, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Originating-Identity", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIOriginatingIdentity)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Originating-Identity: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIOriginatingIdentity = &XBrokerAPIOriginatingIdentity

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ServiceInstanceProvision(c, instanceId, params)
}

// ServiceInstanceLastOperationGet operation middleware
func (siw *ServerInterfaceWrapper) ServiceInstanceLastOperationGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameter("simple", false, "instance_id", c.Param("instance_id"), &instanceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceInstanceLastOperationGetParams

	// ------------- Optional query parameter "service_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "service_id", c.Request.URL.Query(), &params.ServiceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "plan_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "plan_id", c.Request.URL.Query(), &params.PlanId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter plan_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "operation" -------------

	err = runtime.BindQueryParameter("form", true, false, "operation", c.Request.URL.Query(), &params.Operation)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter operation: %s", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ServiceInstanceLastOperationGet(c, instanceId, params)
}

// ServiceBindingUnbinding operation middleware
func (siw *ServerInterfaceWrapper) ServiceBindingUnbinding(c *gin.Context) {

	var err error

	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameter("simple", false, "instance_id", c.Param("instance_id"), &instanceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "binding_id" -------------
	var bindingId string

	err = runtime.BindStyledParameter("simple", false, "binding_id", c.Param("binding_id"), &bindingId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter binding_id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceBindingUnbindingParams

	// ------------- Required query parameter "service_id" -------------

	if paramValue := c.Query("service_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument service_id is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "service_id", c.Request.URL.Query(), &params.ServiceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "plan_id" -------------

	if paramValue := c.Query("plan_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument plan_id is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "plan_id", c.Request.URL.Query(), &params.PlanId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter plan_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "accepts_incomplete" -------------

	err = runtime.BindQueryParameter("form", true, false, "accepts_incomplete", c.Request.URL.Query(), &params.AcceptsIncomplete)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accepts_incomplete: %s", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional header parameter "X-Broker-API-Originating-Identity" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Originating-Identity")]; found {
		var XBrokerAPIOriginatingIdentity OriginatingIdentity
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Originating-Identity, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Originating-Identity", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIOriginatingIdentity)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Originating-Identity: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIOriginatingIdentity = &XBrokerAPIOriginatingIdentity

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ServiceBindingUnbinding(c, instanceId, bindingId, params)
}

// ServiceBindingGet operation middleware
func (siw *ServerInterfaceWrapper) ServiceBindingGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameter("simple", false, "instance_id", c.Param("instance_id"), &instanceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "binding_id" -------------
	var bindingId string

	err = runtime.BindStyledParameter("simple", false, "binding_id", c.Param("binding_id"), &bindingId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter binding_id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceBindingGetParams

	// ------------- Optional query parameter "service_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "service_id", c.Request.URL.Query(), &params.ServiceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "plan_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "plan_id", c.Request.URL.Query(), &params.PlanId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter plan_id: %s", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional header parameter "X-Broker-API-Originating-Identity" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Originating-Identity")]; found {
		var XBrokerAPIOriginatingIdentity OriginatingIdentity
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Originating-Identity, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Originating-Identity", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIOriginatingIdentity)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Originating-Identity: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIOriginatingIdentity = &XBrokerAPIOriginatingIdentity

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ServiceBindingGet(c, instanceId, bindingId, params)
}

// ServiceBindingBinding operation middleware
func (siw *ServerInterfaceWrapper) ServiceBindingBinding(c *gin.Context) {

	var err error

	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameter("simple", false, "instance_id", c.Param("instance_id"), &instanceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "binding_id" -------------
	var bindingId string

	err = runtime.BindStyledParameter("simple", false, "binding_id", c.Param("binding_id"), &bindingId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter binding_id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceBindingBindingParams

	// ------------- Optional query parameter "accepts_incomplete" -------------

	err = runtime.BindQueryParameter("form", true, false, "accepts_incomplete", c.Request.URL.Query(), &params.AcceptsIncomplete)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter accepts_incomplete: %s", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional header parameter "X-Broker-API-Originating-Identity" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Originating-Identity")]; found {
		var XBrokerAPIOriginatingIdentity OriginatingIdentity
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Originating-Identity, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Originating-Identity", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIOriginatingIdentity)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Originating-Identity: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIOriginatingIdentity = &XBrokerAPIOriginatingIdentity

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ServiceBindingBinding(c, instanceId, bindingId, params)
}

// ServiceBindingLastOperationGet operation middleware
func (siw *ServerInterfaceWrapper) ServiceBindingLastOperationGet(c *gin.Context) {

	var err error

	// ------------- Path parameter "instance_id" -------------
	var instanceId string

	err = runtime.BindStyledParameter("simple", false, "instance_id", c.Param("instance_id"), &instanceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter instance_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "binding_id" -------------
	var bindingId string

	err = runtime.BindStyledParameter("simple", false, "binding_id", c.Param("binding_id"), &bindingId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter binding_id: %s", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{""})

	// Parameter object where we will unmarshal all parameters from the context
	var params ServiceBindingLastOperationGetParams

	// ------------- Optional query parameter "service_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "service_id", c.Request.URL.Query(), &params.ServiceId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter service_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "plan_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "plan_id", c.Request.URL.Query(), &params.PlanId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter plan_id: %s", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "operation" -------------

	err = runtime.BindQueryParameter("form", true, false, "operation", c.Request.URL.Query(), &params.Operation)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter operation: %s", err), http.StatusBadRequest)
		return
	}

	headers := c.Request.Header

	// ------------- Required header parameter "X-Broker-API-Version" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Broker-API-Version")]; found {
		var XBrokerAPIVersion APIVersion
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Broker-API-Version, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithLocation("simple", false, "X-Broker-API-Version", runtime.ParamLocationHeader, valueList[0], &XBrokerAPIVersion)
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Broker-API-Version: %s", err), http.StatusBadRequest)
			return
		}

		params.XBrokerAPIVersion = XBrokerAPIVersion

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Header parameter X-Broker-API-Version is required, but not found: %s", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
	}

	siw.Handler.ServiceBindingLastOperationGet(c, instanceId, bindingId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router *gin.Engine, si ServerInterface) *gin.Engine {
	return RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router *gin.Engine, si ServerInterface, options GinServerOptions) *gin.Engine {

	errorHandler := options.ErrorHandler

	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/v2/catalog", wrapper.CatalogGet)

	router.DELETE(options.BaseURL+"/v2/service_instances/:instance_id", wrapper.ServiceInstanceDeprovision)

	router.GET(options.BaseURL+"/v2/service_instances/:instance_id", wrapper.ServiceInstanceGet)

	router.PATCH(options.BaseURL+"/v2/service_instances/:instance_id", wrapper.ServiceInstanceUpdate)

	router.PUT(options.BaseURL+"/v2/service_instances/:instance_id", wrapper.ServiceInstanceProvision)

	router.GET(options.BaseURL+"/v2/service_instances/:instance_id/last_operation", wrapper.ServiceInstanceLastOperationGet)

	router.DELETE(options.BaseURL+"/v2/service_instances/:instance_id/service_bindings/:binding_id", wrapper.ServiceBindingUnbinding)

	router.GET(options.BaseURL+"/v2/service_instances/:instance_id/service_bindings/:binding_id", wrapper.ServiceBindingGet)

	router.PUT(options.BaseURL+"/v2/service_instances/:instance_id/service_bindings/:binding_id", wrapper.ServiceBindingBinding)

	router.GET(options.BaseURL+"/v2/service_instances/:instance_id/service_bindings/:binding_id/last_operation", wrapper.ServiceBindingLastOperationGet)

	return router
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xcbW/bOPL/KoT2/2IXcOI02zd/v7ok7e0Ft90ETVscEBgCLY4sbiVSS1JJs0W++4EP",
	"eqZsObHdXOs3RWzSnOFw5jdPZL8GEc9yzoApGcy+BjkWOAMFwnw6u778BEJSzvQnAjISNFfmY3BnBxAr",
	"sgUIxGOkEkA3IO5oBOhc8M8g0Nn1JVIJVmbsOsUq5iJD9zRNUSEhmARUL5UAJiCCScBwBsEs+M+R/fnR",
	"2fXlUcnAJBDwV0EFkGCmRAGTQEYJZNhyFuMiVcEsOD1+9WswCdRDrheSSlC2DB4fJ8GVoEvKsKJseUmA",
	"Kaoe+nuibqTcTSFBWP4po4piBcR8rzkBqVAseNba2qgdNVg5qnhpbqfL/WM5aA9FPrDoKgeBlTuYXPAc",
	"hKJgxnlzqC8I9w1f/AmRCh4nwQVWOOXL/kLSnqX5myrIzB//JyAOZsFP01pvpo65qTv8oKaChcAPA2Q5",
	"U/BF9Q/hBgDdulF0wdmdlhBncv5zolQuZ9PpkqqkWBxHPJvyHJjjc2EkjHM6bX0xXaR8Mc2wVCCmueAx",
	"TeE4Iz9FlsKR5egXFHOBMi4AEVCYpvI48DD9BstkwbEgFykFpvoyo8Qjda26hAqIVFgI6p0gIRKgRp7Y",
	"WyG4GBBcxwDN1K2ITuYQabm5GUd2yhEYAn7xtUXTYtYjAih31RuhTCrMIggLiRcpNOYsOE8BMz2pyAlW",
	"EArIAauhaT5p/o6lqszpPUheiAj6J7uO/VFMSoWVGQJWZMHsNqAM5YIvBUipIaCIIgACJJgEMaYpkGA+",
	"6ZMau9UaMG8d5bln/+8wZQqY5v2SxXzznd/VLqKvvE0eyoleLkBhghVeo9bltB0CQ6ngmSM1Ehqu7F+1",
	"EOqh6xR7cHpBGRnWFD1K2TIUXNVnXPm5GKcSJp6frTurWEB7JetK+wsNAFlWK0tInbascgld5TJLfKFZ",
	"kYU5T1O9Q1L03JX+zRKEmd3Qi5WEynmPpdP1cJ+nmIXWelbYaO1qVzo7N62r5JSUbr99Gj6lv6lJeV1v",
	"6LRgpOM9t7Ptqtar2GVKbBq5zqWbXi7kQ83S129DrT1qXPrZMKoc7SrGu355hCUMKfje9U1PGh9jGSzp",
	"BViVCrYXKr2MfJApX4ZEYGoCaV4oCGMu7rEw6jUJ7nhaZBBmvGDK63O69BRetmmt+UXHSpyBGGNpntSk",
	"1p9SMvNh7XMK/5aRnFNfOJZwqfwnw4XaiH8TzSge8bSdcKgoDyaVoO2nguh/cZp6JNmRg2GwZGf9Tpte",
	"sr1T+JLr4w+xGghAGdyHC4i5gJFRZpvye5vy9AnjPA+XhbUmArmASKdJHcdSM6KPNxSNKGs8rpnYLIKr",
	"isOoTiFWrVJmGvoMW+ntqh/VVIwRD6BFLoBABFJyUWL10NQKi8n6QKkxt6Y/H3FGTQGtPKm+gmhMeKJm",
	"DIXMkZYOUxSnG4gbnDFvnHZ2wcBjwmPBfcDonqhAFm7LMy1E6tePBkYPTmrC9FMF9Mms8c4g/ahMvXfc",
	"OWfyxzju7+vobqoKU+/gXFra/r6t7J3F++TWM9Dkv88FZwpTBiIk1F8HIFCGnE8S2Rsoq1N2odASaIRJ",
	"CRYDKTcR9A78XGWctFYROsK6X+/63ZKTzsbdgm0mq73PN5HxG/CH6EYHw4izmC7HW6pT4DH+q566gt8y",
	"y1hXz6xzgSHT2tDOS8JNQ9+0aDq0VN/pKiXoolAgvaWBFC8gHWdePaLXAu4oL+QnnBbgSSK5WGJG/zbb",
	"CkcHaKvCnXYMM2IxmePx00dtmd9Raep0Jhw95+TBjySbxYUtUW0QzW47nlwZJJbiHM3fmKjSt/cWoflG",
	"pzIUG+zBiEeoz4rq7nr+tlD5ej5O7VXhRkh0xyFFWeveZWxSbuWjobRlYNlBwmkwP7yrQH8DTep4jKdn",
	"pXOfgCVEhaDqweiEKwZiSaOzQiWmqGm+D2b227qGniiV2y4nfFEgGE7f8KjfeQg+JIB4HNMIp+gqB+Zr",
	"NsscIqqnuGqSsebgaf0B29Wxlm5iNJtUQ4apXlSvcNTphuGc/mPJ+TKFpeBFLjWpugs8wHSPzfv7+2Mf",
	"f8dcLKe92qaRy5A8CMSUgUSYoX99+HD9880vSMOSiHEEaAHqHoBV3Ws9jXRWMc2OlEbgYN1t5SzHUQLo",
	"9Pikxb1jHptRw677qZz+fnnx9o+bt0enxyfHicpSk8BQla4WTNVbCmyjBh2hjC4ThVzQjKIEsyVI26XH",
	"AhDjCj2AQgJSwBKIi+4YzmkwC349PjEs51glRsWmd6fTqO6AL20TtgoHL0kwKzvkv4Ep1TUs+tZvffWU",
	"aeMGxeNcm5N1kIb06clJBSo2IcJ5njrdnf4pbTBaXwtYCTluC8aM2urhdodK2tZWiyzD4iGY6R2bKwzl",
	"NB6jsvFfX91w3yCritoK9f7LKvBtdYdgrtfWIu12HuT0a9UgpeTRGncKFtnb0u5g1hvIy/DiWdKfrJ3t",
	"uyKif9a9I6JFVG4GLYCyJbJ7IeX1D61dtdk3Nr7yFksPff2km+eBpeSRvZdyT1Vixlaz9lcB4qHmrRUT",
	"boU17b2ez1cdnj6DKawzy0RwxguJSK1HSBZ5zsUwdRxFkCsZUqY1xaiph3Ddat+lZZdxQd+wr/6tse30",
	"5HRrtDqpuIfmmZGMRdXXW9ylvdLiIXiOCSp7D4bmq93T/MhwoRIu6N9uo6/2sNHfODO1qdenp/vYYS54",
	"BNJcVUFvHda1/ELTXnAFOFUnucb+Dl7LYP448fvRzszn+tOtIXoJTB1oVxzFoKLkRaH6GBzfDW6vReph",
	"srvEx6EUfxAwX5+83r2B/cEV+icvGPFEW5tbU461Gq6zJ5vAvnSTKkoud2lTLc9fCU3uxvG3Cga70Ol+",
	"ZcKjcfUZmftqjWvKQHoKV59CW8iP30kgs7rFcIhr3Eb3H2qAL9SwyvgUXCzWRxnXLyt7HAbGZpp7wMbx",
	"JU1PR+jZ8Ng8i/0h5Nq2ygrsfPVNubgw5X5ygPFvAuMn/797ohecxSm1DYqXkqI+PUEdV6WcpliqsHU1",
	"YExe23pQsoUkd3y2ShlBmuca1pE5GSB6mKpDJvvcTLbvTa2vIECQfT0YUxCVi6l1x0+yOf5t0mf/6ye/",
	"o5m4d42GifegxMPRWazA8xTtkhHNDkh0nwDTyif09KbbXf3i8cfC7/0WJPZa0PT2mgxG1eFXjVbmlZqx",
	"np3geedZjZx+rS9tj+lJuSt2H1n5LuflNKRaHRYf+DmWv1HDagPqjXv0++yWaaW7T2iUIFxxS+WLbaI9",
	"g93t99Z2nUUeWmuH1tp331qrfUrH0Tmvs76x5ia+9L7aCu+0Y39UAaVhqPy0us/3bdzRoc23/ing/0qX",
	"b5xhr6plu4nnLynqHC5D2Lu/jbhk5yXtQbt215B3atjfRz2988z3qRX0Wtf3Xjbvvk/cZ7F8BO0dlcgP",
	"ceWhJt52PUzrAmzof7ZRQNmwXO6o/7DV8rbT6hzWMxg8BKyHav6hmn+o5r/Eav4oV9R4Smbwv/GI7Hau",
	"zUevVjqHjgK4//Ww/E8hOm+T4AvWkbZ5ldU3/qubc3SRQPTZPDN6x6PPVzfn3SVSHuE04VLNfj05OTGP",
	"etxWvq555oVuWm/THueP/w0AAP//oNRcY31VAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

//lint:file-ignore ST1005 Ignore generated file
